### ISSUE TITLE
Synchronize folders

### ISSUE THREAD

**Issue by kamek-pf** [niqdev/lastpass-operator#6]
Hey there, love the project !

Is it possible to synchronize a full LastPass folder ? 
If I understand correctly, you currently need to write one configuration file for each secret you want to keep in sync.

**Comment by niqdev** [comment]
Hello! Sorry for the late reply...

> Is it possible to synchronize a full LastPass folder ?

Not at the moment, but it's a good idea!

I don't have much free time to add this feature now, but if you want to contribute you are more than welcome 😊

**Comment by niqdev** [comment]
Thanks to @robertoeguia the feature is now implemented
